# Generated by Django 2.2.10 on 2021-01-01 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=101)),
                ('email', models.EmailField(max_length=254)),
                ('message', models.TextField(max_length=400)),
            ],
        ),
    ]
